# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - monAppCda

on:
  push:
    branches:
      - toAzure
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to container registry
        uses: docker/login-action@v2
        with:
          registry: https://index.docker.io/v1/
          username: ${{ secrets.AzureAppService_ContainerUsername_ae1009dcf13a40259f3fd85c04777920 }}
          password: ${{ secrets.AzureAppService_ContainerPassword_4304db6863504c0f976ffa7b224bea28 }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_ae1009dcf13a40259f3fd85c04777920 }}/elgroliero/toazuredevops:${{ github.sha }}
          file: ./Dockerfile

  deploy:
      runs-on: ubuntu-latest
      needs: build
      environment:
        name: 'Production'
        url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

      steps:
        - name: Deploy to Azure Web App
          id: deploy-to-webapp
          uses: azure/webapps-deploy@v2
          with:
            app-name: 'monAppCda'
            slot-name: 'Production'
            publish-profile: ${{ secrets.AzureAppService_PublishProfile_9d978e98fcd942c89ed13fbc4e5348cc }}
            images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_ae1009dcf13a40259f3fd85c04777920 }}/elgroliero/toazuredevops:${{ github.sha }}'
